name: networkboot-dhcpd
services:
    dhcp_server:
        image: networkboot/dhcpd
        container_name: dhcp-server
        network_mode: host
        restart: always
        volumes:
            - type: bind
              source: ./dhcp_pool
              target: /data
              read_only: false
              bind:
                  create_host_path: true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
    db:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: myapp
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - ./container-db-build:/docker-entrypoint-initdb.d/
            - pgdata:/var/lib/postgresql/data
        networks:
            default:
                aliases:
                    - database
    db_admin:
        image: dpage/pgadmin4:latest
        restart: no
        ports:
            - "8080-65535:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${INTERNAL_PGADMIN_EMAIL:-sqladmin@localhost.local}
            PGADMIN_DEFAULT_PASSWORD: ${INTERNAL_PGADMIN_PASSWORD:-password}
        volumes:
            - pgadmin-store:/var/lib/pgadmin
        depends_on:
            - db
volumes:
    pgdata:
    pgadmin-store:
